### ISSUE TITLE
Findbugs fails when JavaSensor uses cached data

### ISSUE THREAD

**Issue by cdlans** [spotbugs/sonar-findbugs#705]
## Issue Description

Findbugs fails with the error `One (sub)project contains Java source files that are not compiled`.  However, the source files are compiled. This only occurs when the SonarQube JavaSensor uses caching. The JavaSensor uses caching when we open a merge request and use the Jenkins Gitlab plugin (v1.6.0).
```
[2023-01-12T21:16:13.099Z] [INFO] 21:16:12.862 The Java analyzer is running in a context where unchanged files can be skipped. Full analysis is performed for changed files, optimized analysis for unchanged files.
[2023-01-12T21:16:13.099Z] [DEBUG] 21:16:12.863 'XXXXXX-XXX-logging/src/main/java/com/XXXXXXXXXX/XXXXXX/XXX/logging/LoggingInterceptor.java' generated metadata with charset 'UTF-8'
[2023-01-12T21:16:13.099Z] [INFO] 21:16:12.864 Server-side caching is enabled. The Java analyzer was able to leverage cached data from previous analyses for 1 out of 1 files. These files will not be parsed.
```

I suspect Findbugs depends on some result or file from the JavaSensor, but it is not there when the JavaSensor uses the cache.

Workaround: when disabling caching, the error does not occur anymore: `-D sonar.java.skipUnchanged=false`.

See the log attached: [jenkins_log.txt](https://github.com/spotbugs/sonar-findbugs/files/10410115/jenkins_log.txt)

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 9.8 (build 63668)   |
| Sonar-FindBugs     | 4.2.2   |
| Maven              | 3.6.0   |
| Gradle             | n/a   |
| Java               | Corretto 17.0.4   |

**Comment by gtoison** [comment]
Thanks for the detailed error report and it's great that you are using SonarQube 9.8 because https://github.com/SonarSource/sonar-java/pull/4175 should be incorporated in that version.
That change should make it possible to stop relying on a side effect of the JavaSensor
I need to find a way for this to work while remaining compatible on earlier SonarQube versions because the new API methods will be missing

**Comment by gtoison** [comment]
Hello, pull request #706 should fix the problem when running on SonarQube 9.8 (or above hopefully). It uses the new java plugin API to get the binary directories instead of relying on the old behavior (getting the .class files corresponding to the sources analyzed by the native java plugin).

With that change the binaries of unit tests should also be analyzed.
When running on SonarQube 9.7 and before the behavior should be unchanged.

I cannot test that this fixes your problem for PR/cached analysis because I only have access to a community edition SonarQube server.
Would you be able test the fix? You can build it yourself from the branch corresponding to the PR by running `mvn package` and getting the `sonar-findbugs-plugin.jar` file from the `target` folder.
Unfortunately Github won't let me upload the jar file here

**Comment by cdlans** [comment]
It took a while, but I tested the fix. It did run without crashing, but I saw the following in the Jenkins log, so I am not sure if the test was successful:
```
[2023-02-02T16:44:15.258Z] [INFO] 16:44:15.213 JavaResourceLocator.testClassPath() not available before SonarQube 9.8
[2023-02-02T16:44:15.258Z] [DEBUG] 16:44:15.214 Error calling JavaResourceLocator.testClassPath()
[2023-02-02T16:44:15.258Z] java.lang.NoSuchMethodException: org.sonar.plugins.java.api.JavaResourceLocator.testClassPath()
```
See the log attached: [jenkins_findbugs_preview_3.log](https://github.com/spotbugs/sonar-findbugs/files/10571687/jenkins_findbugs_preview_3.log)


Could it be an issue with reflection on Java 17? Or would that throw a different exception?

Furthermore, while I was setting up the test, I was recreating the problem with findbugs plugin version 4.2.2: I removed the `-D sonar.java.skipUnchanged=false` workaround. But to my surprise the problem didn't reoccur. The logs say the JavaSensor is caching again, but now it works.

Maybe I experienced the issue because the cache was corrupt, due to the SonarQube upgrade that was just performed?

**Comment by gtoison** [comment]
Thanks a lot for testing, your message made me realize I made a mistake in a method name!
The error you see is when it tries to get the libraries of your unit tests (libraries such as JUnit, Mockito etc.) and this is failing because the method I should be calling is `testClasspath`, not `testClassPath`.
I'll push a fix later today, in the meantime the issue is here: https://github.com/spotbugs/sonar-findbugs/pull/706/files#r1094870055

This should only affect the analysis of the unit tests of the project. Before that change the tests were not analyzed at all because there was no way to get the compiled `.class` files for tests.

Actually it might be safer to make that optional and add a new `sonar.findbugs.analyzeTests` option...

**Comment by gtoison** [comment]
It should be better fix the commit I've just pushed on the PR branch, the issue only prevented SpotBugs to get the tests libraries so I think it was working for the most part.
Thanks again for testing!

Regarding the behavior you saw maybe changing the plugins invalidates the analysis cache?

**Comment by cdlans** [comment]
> Regarding the behavior you saw maybe changing the plugins invalidates the analysis cache?

The 4.2.2 version started working before we changed the plugin. And we first updated to 4.2.2 when the issue occurred, because we were still on an older version, but that didn't fix it. But 3 weeks have passed since the issue occurred, so it might well be that the cache has been refreshed in the meantime.

Do you want me to test with the new commit?

**Comment by gtoison** [comment]
If you have time you can test with the new commit, this should only affect the analysis of your unit tests though, there rest was fine.
SonarQube 9.9 LTS is due soon, I think I'll wait for the release to check that everything still works and then I'll publish a new version of the plugin

What I suspect might be happening for the cached analysis issue is that no java files are analyses (e.g. the only change was a configuration file). When that happen I think you would get the error message you have reported.
In case some java files are modified then the plugin should analyze them without an error

**Comment by gtoison** [comment]
This should be fixed in version 4.2.3 (just released)

**Comment by NoSugarCoffee** [comment]
> This should be fixed in version 4.2.3 (just released) Note that the fix needs the SonarQube version to be >= 9.8

How about the pre-9.8 sonarQube works with 4.2.3? And the compatibility part did not hightlight it.

**Comment by gtoison** [comment]
The fix uses a new API introduced in SonarQube 9.8
In earlier versions the problem remains when SonarQube uses cached analysis; so the plugin is compatible with a known issue

**Comment by NoSugarCoffee** [comment]
> The fix uses a new API introduced in SonarQube 9.8 In earlier versions the problem remains when SonarQube uses cached analysis; so the plugin is compatible with a known issue

Yeah, i see. I mean is there a solution to work with pre-9.5 and 4.2.3/4.2.4? For us, we currently use sonarQube9.5 and 4.0.5. But in order to support JDK21. So we bump the findbugs to 4.2.4 but met the issue here. And we didn't want to upgrade sonarQube here for some reasons. So the workaround is patching a version based on 4.0.5 (asm 9.5) just to support JDK21 and work with 9.5 :face_exhaling:

**Comment by gtoison** [comment]
The underlying issue with cached data was always there from what I've seen, it appeared when SonarQube started using it from the built-in java sensor. Upgrading the findbugs plugin from to 4.2.4 should not cause the issue.
If from some reason you need to stay on 9.5 and support JDK 21 you should disable the cached analysis and upgrade to 4.2.4

**Comment by NoSugarCoffee** [comment]
How can i close cached analysis for SonarQube community version? It seems `sonar.java.skipUnchanged` is a pull-request feature that works for non-community version.

**Comment by gtoison** [comment]
I don't know enough the inner workings of SonarQube well enough to say for sure, but they went through several iterations through the 9.x series to get cached analysis working. The 9.5 version was probably not the most stable on that new feature.
Can you try `sonar.java.skipUnchanged` to see if it's any better?

**Comment by NoSugarCoffee** [comment]
Didn't work for `sonar.java.skipUnchanged`

```
[INFO] 17:16:45.934 The Java analyzer cannot skip unchanged files in this context. A full analysis is performed for all files.
```
and same error as @cdlans said

**Comment by gtoison** [comment]
Hum, I'm not sure why it's not working but again, SonarSource went through several iterations on the cached analysis feature.  It is quite possible that it was not _quite_ working yet in 9.5
I think your best route from here is to prioritize the upgrade to 9.8 (or while you're at it 9.9 LTS)

**Comment by NoSugarCoffee** [comment]
Cool, thanks for your advice. @gtoison
